# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weatherAppObj' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

	pod 'AFNetworking', '~> 3.0' 
	pod 'JSONModel' 
	pod 'MBProgressHUD'

  # Pods for weatherAppObj

  target 'weatherAppObjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weatherAppObjUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
